apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: someone
  lifecycle: experimental
  system: backstage
